# Generated by Django 4.2.2 on 2023-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_profile_id_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default-avatar.png", null=True, upload_to="users/"
            ),
        ),
    ]
